version: '2'
services:
  es1:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.0.2
    container_name: es1
    environment:
      - cluster.name=elasticsearch
      - bootstrap.memory_lock=true
      - node.name=es1
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: 1g
    cap_add:
      - IPC_LOCK
    volumes:
      - ./esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - esnet
  es2:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.0.2
    container_name: es2
    environment:
      - cluster.name=elasticsearch
      - bootstrap.memory_lock=true
      - node.name=es2
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.ping.unicast.hosts=es1"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: 1g
    cap_add:
      - IPC_LOCK
    volumes:
      - ./esdata2:/usr/share/elasticsearch/data
    networks:
      - esnet

volumes:
  esdata1:
    driver: local
  esdata2:
    driver: local

networks:
  esnet:
    driver: bridge
